apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
        - name: config-volume
          configMap:
            name: log-output-configmap
      containers:
        - name: log-writer
          image: log-output-writer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
          volumeMounts:
            - name: shared-data
              mountPath: /shared
            - name: config-volume
              mountPath: /config
        - name: log-reader
          image: log-output-reader:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-project-configmap
                  key: TODO_BACKEND_URL
            - name: TODO_MAX_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: todo-project-configmap
                  key: TODO_MAX_LENGTH
          volumeMounts:
            - name: shared-data
              mountPath: /shared
