apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: log-writer
          image: log-output-writer:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-data
              mountPath: /shared
        - name: log-reader
          image: log-output-reader:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-data
              mountPath: /shared
