apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
  labels:
    app: todo-app
    managed-by: argocd
    gitops: enabled
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
