apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-backend-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/haseeb1496/kubernetes-basics.git
    targetRevision: v1.0.0-production
    path: todo-backend/environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
