apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: todo-staging
  labels:
    app: todo-app
    environment: staging
    managed-by: argocd
    gitops: enabled
spec:
  selector:
    app: todo-app
    environment: staging
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP