apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-staging
  labels:
    app: todo-backend
    environment: staging
    managed-by: argocd
    gitops: enabled
spec:
  selector:
    app: todo-backend
    environment: staging
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP