apiVersion: v1
kind: Service
metadata:
  name: wikipedia-server
  labels:
    app: wikipedia-server
spec:
  type: ClusterIP
  selector:
    app: wikipedia-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
